### ISSUE TITLE
How to start this app

### ISSUE THREAD

**Issue by arshadalisoomro** [vzhyhunou/vzh-cms#116]
I was looking for Spring and ReactJS example project and luckily found this one. I have a question about how to start the frontend of this project. If I run the project as a normal Spring Boot App and go to `http://localhost:8090/`  I get the error :

![reactSpring](https://user-images.githubusercontent.com/2489546/79318352-4ca84a80-7f20-11ea-976f-4c73125c119b.PNG)

Please help me in this case.

**Comment by vzhyhunou** [comment]
Hi,
Actually you can start the app in two steps just make sure you have JDK 1.8 installed:

1. Build the project by following command: `./mvnw clean install`
2. Run created JAR: `java -jar target/vzh-cms-0.0.1-SNAPSHOT-exec.jar`

Then you will be able to open `http://localhost:8090`

Best regards!
